

GET http://localhost:8080/users/1

### Post request
POST http://localhost:8080/users
Content-Type: application/json

{
    "id": 1,
    "first_name": "ankit",
    "last_name": "agrawal",
    "email": "ankit@agrawal.com",
    "date_created":""
}



### Ping pong
GET http://localhost:8080/ping
